### ISSUE TITLE
Can't reset password after attempting an invalid password

### ISSUE THREAD

**Issue by alexwholland** [alexwholland/password-manager#1]
### Issue Type
Bug Report

### OS / Environment
macOS 12.5

### Component
`manager.py`

### Steps
Precondition: A master password is already stored in the database and the recovery key is saved
1. Open the application
2. enter an invalid master password and click "Submit"
3. Click "Reset Password"
4. Enter the recovery key and click "Check Key"
5. enter a new master password in both fields and press "Save"

### Expected Results
- The new master password is added to the database and the user is directed to the main password manager GUI

### Actual Results
- The user is not able to create a new master password

### Error Message
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/alex/PycharmProjects/password-manager/manager.py", line 116, in savePassword
    encryptionKey = base64.urlsafe_b64encode(kdf.derive(txt.get().encode()))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/primitives/kdf/pbkdf2.py", line 48, in derive
    raise AlreadyFinalized("PBKDF2 instances can only be used once.")
cryptography.exceptions.AlreadyFinalized: PBKDF2 instances can only be used once.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/alex/PycharmProjects/password-manager/manager.py", line 116, in savePassword
    encryptionKey = base64.urlsafe_b64encode(kdf.derive(txt.get().encode()))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/primitives/kdf/pbkdf2.py", line 48, in derive
    raise AlreadyFinalized("PBKDF2 instances can only be used once.")
cryptography.exceptions.AlreadyFinalized: PBKDF2 instances can only be used once.
```

### Note
- The issue does not occur when step 2 is skipped

**Comment by alexwholland** [comment]
Proposed fix from commit fa1eb6e589e22e85726ae9a9aa0ffe0a708117f2 can not verify password on secondary login. This issue has been reopened and the commit has been reverted. 

Error message:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/alex/PycharmProjects/password-manager/manager.py", line 226, in checkPassword
    vaultScreen()
  File "/Users/alex/PycharmProjects/password-manager/manager.py", line 305, in vaultScreen
    lbl1 = Label(window, text=(decrypt(array[i][1], encryptionKey)), font=("Helvetica", 12))
  File "/Users/alex/PycharmProjects/password-manager/manager.py", line 35, in decrypt
    return Fernet(token).decrypt(message)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/fernet.py", line 33, in __init__
    key = base64.urlsafe_b64decode(key)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/base64.py", line 131, in urlsafe_b64decode
    s = _bytes_from_decode_data(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'int'
```
